# ============================================================
# APPLICATION
# ============================================================

spring.application.name=api-gateway


# ============================================================
# HTTPS
# ============================================================

server.ssl.enabled=true

server.ssl.key-store=${GATEWAY_TLS_KEYSTORE_PATH}
server.ssl.key-store-password=${GATEWAY_TLS_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=${GATEWAY_TLS_KEY_ALIAS:1}


# ============================================================
# GATEWAY HTTP CLIENT
# ============================================================

spring.cloud.gateway.server.webflux.httpclient.connect-timeout=${GATEWAY_CONNECT_TIMEOUT_MS:5000}
spring.cloud.gateway.server.webflux.httpclient.response-timeout=${GATEWAY_RESPONSE_TIMEOUT:30s}
spring.cloud.gateway.server.webflux.httpclient.ssl.trusted-x509-certificates[0]=${MKCERT_CA}


# ============================================================
# GATEWAY ROUTES
# ============================================================

spring.cloud.gateway.server.webflux.routes[0].id=user-auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-account
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[2].id=user-admin
spring.cloud.gateway.server.webflux.routes[2].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/admin/**

spring.cloud.gateway.server.webflux.routes[3].id=product-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/products/**

spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.server.webflux.routes[5].id=payment-service-read
spring.cloud.gateway.server.webflux.routes[5].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/payments/*


# ============================================================
# GATEWAY SECURITY
# ============================================================

gateway.security.access-token-cookie-name=${ACCESS_TOKEN_COOKIE_NAME:__Host-access_token}
gateway.security.issuer=${JWT_ISSUER:user-service}
gateway.security.public-key-path=${GATEWAY_JWT_PUBLIC_KEY_PATH:${JWT_PUBLIC_KEY_PATH}}
