# ============================================================
# API GATEWAY - LOCAL
# ============================================================

server.port=${GATEWAY_PORT:8442}
server.address=${GATEWAY_ADDRESS:localhost}
