# ============================================================
# LOCAL ENVIRONMENT
# ============================================================


# ============================================================
# EUREKA
# ============================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ============================================================
# EUREKA INSTANCE
# ============================================================

eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

eureka.instance.secure-port=${server.port}
eureka.instance.instance-id=${spring.application.name}:${server.port}
