# ============================================================
# PRODUCTION ENVIRONMENT
# ============================================================

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true

eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}

eureka.instance.secure-port=${server.port}
eureka.instance.instance-id=${spring.application.name}:${server.port}
