# ============================================================
# ORDER SERVICE - LOCAL
# ============================================================

server.port=8445

product.service.base-url=https://localhost:8444
product.service.connect-timeout=5s
product.service.read-timeout=10s

payment.service.base-url=https://localhost:8446
payment.service.connect-timeout=5s
payment.service.read-timeout=15s
