# ============================================================
# APPLICATION
# ============================================================

spring.application.name=payment-service


# ============================================================
# HTTPS
# ============================================================

server.ssl.enabled=true
server.ssl.key-store=file:${TLS_KEYSTORE_PATH}
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${TLS_KEYSTORE_PASSWORD}
server.ssl.key-alias=1
server.ssl.client-auth=want


# ============================================================
# DATABASE
# ============================================================

spring.datasource.url=${PAYMENT_DB_URL}
spring.datasource.username=${PAYMENT_DB_USERNAME}
spring.datasource.password=${PAYMENT_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# ============================================================
# JWT
# ============================================================

security.jwt.issuer=${JWT_ISSUER}
security.jwt.public-key-path=${PAYMENT_JWT_PUBLIC_KEY_PATH}


# ============================================================
# OUTBOUND SERVICE mTLS
# ============================================================

service.mtls.client-key-store-path=${TLS_CLIENT_KEYSTORE_PATH}
service.mtls.client-key-store-password=${TLS_CLIENT_KEYSTORE_PASSWORD}

service.mtls.trust-store-path=${TLS_TRUSTSTORE_PATH}
service.mtls.trust-store-password=${TLS_TRUSTSTORE_PASSWORD}


# ============================================================
# PAYMENT PROVIDER
# ============================================================

payment.provider.mock.enabled=true

payment.idempotency-record-ttl=15m
payment.idempotency-key-max-length=128
