package com.microservice.one.identity.util;

import org.springframework.security.crypto.factory.PasswordEncoderFactories;
import org.springframework.security.crypto.password.PasswordEncoder;

import com.microservice.one.identity.dto.request.LoginRequest;
import com.microservice.one.identity.dto.request.RefreshTokenRequest;
import com.microservice.one.identity.dto.request.RegisterRequest;
import com.microservice.one.identity.dto.request.UpdateUserRequest;
import com.microservice.one.identity.entity.User;
import com.microservice.one.identity.enums.Role;

public final class TestDataFactory {

    private static final PasswordEncoder PASSWORD_ENCODER =
            PasswordEncoderFactories
                    .createDelegatingPasswordEncoder();

    private TestDataFactory() {
    }

    /*
     * ============================================================
     * REGISTER REQUESTS
     * ============================================================
     */

    public static RegisterRequest registerRequest() {

        return new RegisterRequest(
                "Swatantra",
                "Naskar",
                "swata@example.com",
                "Password@123");

    }

    public static RegisterRequest duplicateEmailRequest() {

        return new RegisterRequest(
                "Another",
                "User",
                "swata@example.com",
                "Password@123");

    }

    public static RegisterRequest adminRegisterRequest() {

        return new RegisterRequest(
                "Admin",
                "User",
                "admin@example.com",
                "Admin@123");

    }

    /*
     * ============================================================
     * LOGIN REQUESTS
     * ============================================================
     */

    public static LoginRequest loginRequest() {

        return new LoginRequest(
                "swata@example.com",
                "Password@123",
                "windows-desktop");

    }

    public static LoginRequest invalidPasswordRequest() {

        return new LoginRequest(
                "swata@example.com",
                "WrongPassword@123",
                "windows-desktop");

    }

    public static LoginRequest unknownUserRequest() {

        return new LoginRequest(
                "unknown@example.com",
                "Password@123",
                "windows-desktop");

    }

    public static LoginRequest mobileLoginRequest() {

        return new LoginRequest(
                "swata@example.com",
                "Password@123",
                "android-phone");

    }

    /*
     * ============================================================
     * REFRESH TOKEN REQUESTS
     * ============================================================
     */

    public static RefreshTokenRequest refreshTokenRequest(
            String refreshToken) {

        return new RefreshTokenRequest(
                refreshToken,
                "windows-desktop");

    }

    public static RefreshTokenRequest mobileRefreshTokenRequest(
            String refreshToken) {

        return new RefreshTokenRequest(
                refreshToken,
                "android-phone");

    }

    /*
     * ============================================================
     * UPDATE USER REQUEST
     * ============================================================
     */

    public static UpdateUserRequest updateUserRequest() {

        return new UpdateUserRequest(
                "UpdatedFirstName",
                "UpdatedLastName");

    }

    /*
     * ============================================================
     * USER ENTITIES
     * ============================================================
     */

    public static User user() {

        User user = new User();

        /*
         * Do NOT assign userId here.
         *
         * User.userId is generated by Hibernate using
         * @UuidGenerator.
         */
        user.setFirstName("Swatantra");

        user.setLastName("Naskar");

        user.setEmail("swata@example.com");

        user.setPasswordHash(
                PASSWORD_ENCODER.encode(
                        "Password@123"));

        user.setRole(
                Role.ROLE_USER);

        user.setEnabled(true);

        user.setAccountNonLocked(true);

        return user;

    }

    public static User adminUser() {

        User user = new User();

        /*
         * Do NOT assign userId here.
         *
         * User.userId is generated by Hibernate using
         * @UuidGenerator.
         */
        user.setFirstName("Admin");

        user.setLastName("User");

        user.setEmail("admin@example.com");

        user.setPasswordHash(
                PASSWORD_ENCODER.encode(
                        "Admin@123"));

        user.setRole(
                Role.ROLE_ADMIN);

        user.setEnabled(true);

        user.setAccountNonLocked(true);

        return user;

    }

    public static User disabledUser() {

        User user = new User();

        /*
         * Do NOT assign userId here.
         *
         * User.userId is generated by Hibernate using
         * @UuidGenerator.
         */
        user.setFirstName("Disabled");

        user.setLastName("User");

        user.setEmail("disabled@example.com");

        user.setPasswordHash(
                PASSWORD_ENCODER.encode(
                        "Password@123"));

        user.setRole(
                Role.ROLE_USER);

        user.setEnabled(false);

        user.setAccountNonLocked(true);

        return user;

    }

    public static User lockedUser() {

        User user = new User();

        /*
         * Do NOT assign userId here.
         *
         * User.userId is generated by Hibernate using
         * @UuidGenerator.
         */
        user.setFirstName("Locked");

        user.setLastName("User");

        user.setEmail("locked@example.com");

        user.setPasswordHash(
                PASSWORD_ENCODER.encode(
                        "Password@123"));

        user.setRole(
                Role.ROLE_USER);

        user.setEnabled(true);

        user.setAccountNonLocked(false);

        return user;

    }

}