spring.application.name=MicroserviceConfigServer

server.port=8000
server.servlet.context-path=/config-server

# ============================================================
# GIT CONFIGURATION REPOSITORY
# ============================================================

spring.cloud.config.server.git.uri=git@github.com:CODEXLeo/MicroserviceConfigRepo.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true