spring.application.name=MicroserviceConfigServer

server.port=8000
server.servlet.context-path=/config-server

# ============================================================
# GIT CONFIGURATION REPOSITORY
# ============================================================

spring.cloud.config.server.git.uri=git@github.com:CODEXLeo/MicroserviceConfigRepo.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# ============================================================
# GIT SSH AUTHENTICATION
# ============================================================

spring.cloud.config.server.git.ignore-local-ssh-settings=true
spring.cloud.config.server.git.private-key=${CONFIG_SERVER_GIT_PRIVATE_KEY}

spring.cloud.config.server.git.known-hosts-file=${user.home}/.ssh/known_hosts
spring.cloud.config.server.git.strict-host-key-checking=true